<?php

return [
    'APP_NAME'               => 'ClientScope',
    'APIKEY'                 => 'api.Pd*!(5675',
    'SECRET_KEY'             => 'api.Pd*jLDHC8[SG&SIH[(!(5675',
    'PAGINATION_LIMIT'       => 25,
    'DATATABLE_RECORD_LIMIT' => 25,
    'ADMIN_DATE_TIME_FORMAT' => 'd-m-Y h:i a',
    'CACHE_EXPIRY_TIME'      => 86400,
    'GOOGLE_MAP_API_KEY'     => 'AIzaSyDfNLqbUALiCx95Zk_8MNe26PBCnmY3uCs',
    'DROPZONE_FILE_PATH'     => public_path('storage/dropzone'),
    'TEAM_IMAGE_PATH'        => 'uploads/team/',
    'KPI_STATUSES'           => [
        'attempts',
        'contacts',
        'qualified',
        'leads',
        'sales'
    ],
    'RADIUS'                 => 10,
    'PIN_GRID_COLUMN'        => [
        'Address',
        'Created By',
        'Assign To',
        'Status',
        'Territory',
        'Updated By',
        'House Number',
        'Unit',
        'State',
        'City',
        'Zip Code',
        'Latitude',
        'Longitude',
        'Name',
        'Phone',
        'Email',
        'Created Date',
        'Update Date',
        'Appointment Title',
        'Notes',
        'Last Status Modified Date',
        'Number Of Status Changes'
    ],
    'PIN_STATUS_IMAGES' => [
        '#FF7F00' => 'assets/images/1.png',
        '#45E5CB' => 'assets/images/2.png',
        '#453E4A' => 'assets/images/3.png',
        '#CC7A7A' => 'assets/images/4.png',
        '#8C0707' => 'assets/images/5.png',
        '#ACA46F' => 'assets/images/6.png',
        '#327311' => 'assets/images/7.png',
        '#00AAFF' => 'assets/images/8.png',
        '#FF59D6' => 'assets/images/9.png',
        '#92F22A' => 'assets/images/10.png',
        '#7E00D9' => 'assets/images/11.png',
        '#E4E4E4' => 'assets/images/12.png',
        '#FFD400' => 'assets/images/13.png',
        '#45CF00' => 'assets/images/14.png',
        '#0040FF' => 'assets/images/15.png',
        '#660A0A' => 'assets/images/16.png',
        '#959195' => 'assets/images/17.png'
    ],
];